apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: daemon.standalone.yml
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: daemon
    name: daemon
  spec:
    ports:
    - name: 8090-tcp
      port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
      app: daemon
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 4
    labels:
      app: daemon
    name: daemon
  spec:
    replicas: 1
    selector:
      app: daemon
      deploymentconfig: daemon
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/container.daemon.image.entrypoint: '["daemon"]'
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: daemon
          deploymentconfig: daemon
      spec:
        containers:
        - env:
          - name: WITH_HUB
            value: "false"
          - name: DAEMON_TYPE
            value: POD
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          image: ${IMAGE_SPEC}
          imagePullPolicy: IfNotPresent
          name: daemon
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    observedGeneration: 4
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: daemon
    name: daemon
  spec:
    host: ${DAEMON_PUBLIC_ROUTE}
    port:
      targetPort: 8090-tcp
    to:
      kind: Service
      name: daemon
      weight: 100
parameters:
- description: The public route of the daemon
  name: DAEMON_PUBLIC_ROUTE
  required: true
  value: daemon.namespace.defaultroute.com
- description: The pull spec of the image
  name: IMAGE_SPEC
  required: true
  value: 172.30.151.39:5000/project/daemon